<script setup>
import { computed, onMounted, reactive, ref } from 'vue'
const tab=ref('colleges'),colleges=ref([]),templates=ref([]),keyword=ref(''),loading=ref(false),notice=ref('')
const collegeForm=reactive({id:null,name:'',description:''}),templateForm=reactive({id:null,name:'',type:'COURSE',collegeId:'',description:''})
const collegeModal=ref(false),templateModal=ref(false),typeFilter=ref(''),statusFilter=ref('')
const collegeNames=computed(()=>Object.fromEntries(colleges.value.map(c=>[c.id,c.name])))
async function request(method,path,body){const r=await fetch(path,{method,headers:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});const data=await r.json();if(data.code!==200)throw new Error(data.message||'请求失败');return data}
function tip(t){notice.value=t;setTimeout(()=>notice.value='',2000)}
async function loadColleges(){loading.value=true;try{const r=await request('GET','/api/admin/colleges'+(keyword.value?'?keyword='+encodeURIComponent(keyword.value):''));colleges.value=r.data||[]}catch(e){tip(e.message)}finally{loading.value=false}}
async function loadTemplates(){loading.value=true;try{const q=new URLSearchParams();if(typeFilter.value)q.set('type',typeFilter.value);if(statusFilter.value!=='')q.set('status',statusFilter.value);const r=await request('GET','/api/admin/templates'+(q.size?'?'+q:''));templates.value=r.data||[]}catch(e){tip(e.message)}finally{loading.value=false}}
function openCollege(c){Object.assign(collegeForm,c?{id:c.id,name:c.name,description:c.description||''}:{id:null,name:'',description:''});collegeModal.value=true}
async function saveCollege(){if(!collegeForm.name.trim())return tip('学院名称不能为空');try{const body={name:collegeForm.name.trim(),description:collegeForm.description.trim()};await request(collegeForm.id?'PUT':'POST',collegeForm.id?'/api/admin/colleges/'+collegeForm.id:'/api/admin/colleges',body);collegeModal.value=false;await loadColleges();tip('保存成功')}catch(e){tip(e.message)}}
async function removeCollege(c){if(!confirm(`确定删除“${c.name}”吗？`))return;try{await request('DELETE','/api/admin/colleges/'+c.id);await loadColleges();tip('删除成功')}catch(e){tip(e.message)}}
function openTemplate(t){Object.assign(templateForm,t?{id:t.id,name:t.name,type:t.type,collegeId:String(t.collegeId),description:t.description||''}:{id:null,name:'',type:'COURSE',collegeId:colleges.value[0]?.id?String(colleges.value[0].id):'',description:''});templateModal.value=true}
async function saveTemplate(){if(!templateForm.name||!templateForm.collegeId)return tip('模板名称和所属学院不能为空');const body={name:templateForm.name,type:templateForm.type,collegeId:Number(templateForm.collegeId),description:templateForm.description,status:0,structureJson:'[]',formatJson:'{}',coverFields:'[]'};try{await request(templateForm.id?'PUT':'POST',templateForm.id?'/api/admin/templates/'+templateForm.id:'/api/admin/templates',body);templateModal.value=false;await loadTemplates();tip('保存成功')}catch(e){tip(e.message)}}
async function switchStatus(t){try{await request('PUT',`/api/admin/templates/${t.id}/status?status=${t.status===1?0:1}`);await loadTemplates();tip('状态已更新')}catch(e){tip(e.message)}}
async function removeTemplate(t){if(!confirm(`确定删除“${t.name}”吗？`))return;try{await request('DELETE','/api/admin/templates/'+t.id);await loadTemplates();tip('删除成功')}catch(e){tip(e.message)}}
function switchTab(v){tab.value=v;v==='colleges'?loadColleges():loadTemplates()}
onMounted(async()=>{await loadColleges();await loadTemplates()})
</script>
<template><section class="admin-vue"><div class="admin-tabs"><button :class="{active:tab==='colleges'}" @click="switchTab('colleges')">学院管理</button><button :class="{active:tab==='templates'}" @click="switchTab('templates')">模板管理</button></div>
<div v-if="tab==='colleges'" class="admin-card"><div class="admin-head"><b>学院列表</b><div><input v-model="keyword" placeholder="搜索学院名称" @keyup.enter="loadColleges"><button @click="loadColleges">搜索</button><button class="admin-primary" @click="openCollege()">＋ 新增学院</button></div></div><div class="admin-table"><div class="admin-tr admin-th"><span>ID</span><span>学院名称</span><span>描述</span><span>创建时间</span><span>操作</span></div><div v-if="loading" class="admin-empty">正在加载…</div><div v-else-if="!colleges.length" class="admin-empty">暂无学院数据</div><div v-for="c in colleges" :key="c.id" class="admin-tr"><span>{{c.id}}</span><b>{{c.name}}</b><span>{{c.description||'—'}}</span><span>{{c.createTime?.replace('T',' ').slice(0,16)||'—'}}</span><span><button @click="openCollege(c)">编辑</button><button class="admin-danger" @click="removeCollege(c)">删除</button></span></div></div></div>
<div v-else class="admin-card"><div class="admin-head"><b>模板列表</b><div><select v-model="typeFilter" @change="loadTemplates"><option value="">全部类型</option><option value="COURSE">课程论文</option><option value="GRADUATION">毕业论文</option><option value="PROJECT">项目论文</option></select><select v-model="statusFilter" @change="loadTemplates"><option value="">全部状态</option><option value="1">已启用</option><option value="0">已停用</option></select><button class="admin-primary" @click="openTemplate()">＋ 新增模板</button></div></div><div class="admin-table"><div class="admin-tr template admin-th"><span>模板名称</span><span>类型</span><span>所属学院</span><span>版本/状态</span><span>操作</span></div><div v-if="loading" class="admin-empty">正在加载…</div><div v-else-if="!templates.length" class="admin-empty">暂无模板数据</div><div v-for="t in templates" :key="t.id" class="admin-tr template"><b>{{t.name}}</b><span>{{t.type}}</span><span>{{collegeNames[t.collegeId]||t.collegeId}}</span><span>V{{t.version}} · {{t.status===1?'已启用':'已停用'}}</span><span><button @click="openTemplate(t)">编辑</button><button @click="switchStatus(t)">{{t.status===1?'停用':'启用'}}</button><button class="admin-danger" @click="removeTemplate(t)">删除</button></span></div></div></div>
<div v-if="collegeModal||templateModal" class="admin-overlay" @click.self="collegeModal=templateModal=false"><div class="admin-dialog"><h3>{{collegeModal?(collegeForm.id?'编辑学院':'新增学院'):(templateForm.id?'编辑模板':'新增模板')}}</h3><template v-if="collegeModal"><label>学院名称<input v-model="collegeForm.name"></label><label>描述<textarea v-model="collegeForm.description"></textarea></label></template><template v-else><label>模板名称<input v-model="templateForm.name"></label><label>论文类型<select v-model="templateForm.type"><option value="COURSE">课程论文</option><option value="GRADUATION">毕业论文</option><option value="PROJECT">项目论文</option></select></label><label>所属学院<select v-model="templateForm.collegeId"><option v-for="c in colleges" :key="c.id" :value="c.id">{{c.name}}</option></select></label><label>描述<textarea v-model="templateForm.description"></textarea></label></template><div><button @click="collegeModal=templateModal=false">取消</button><button class="admin-primary" @click="collegeModal?saveCollege():saveTemplate()">保存</button></div></div></div><div v-if="notice" class="admin-notice">{{notice}}</div></section></template>
<style scoped>
.admin-vue{padding:24px 30px;max-width:1250px;margin:auto}.admin-tabs{display:flex;gap:8px;margin-bottom:16px}.admin-tabs button{padding:9px 16px}.admin-tabs .active{background:#4f776a;color:#fff;border-color:#4f776a}.admin-card{background:#fff;border:1px solid #e4e3de;border-radius:13px;overflow:hidden}.admin-head{padding:16px 18px;border-bottom:1px solid #e4e3de;display:flex;align-items:center;justify-content:space-between}.admin-head>div{display:flex;gap:8px}.admin-head input{width:210px}.admin-primary{background:#4f776a;color:#fff;border-color:#4f776a}.admin-table{width:100%}.admin-tr{display:grid;grid-template-columns:60px 1.2fr 1.5fr 150px 170px;gap:12px;align-items:center;padding:13px 18px;border-bottom:1px solid #eee}.admin-tr.template{grid-template-columns:1.3fr .7fr 1fr .8fr 230px}.admin-th{background:#f6f5f2;color:#777;font-size:12px;font-weight:700}.admin-tr>span:last-child{display:flex;gap:5px}.admin-danger{color:#a8544d}.admin-empty{text-align:center;padding:50px;color:#888}.admin-overlay{position:fixed;inset:0;background:#0006;z-index:30;display:grid;place-items:center}.admin-dialog{width:500px;background:#fff;padding:22px;border-radius:13px}.admin-dialog h3{margin-top:0}.admin-dialog label{display:block;margin:12px 0;color:#666}.admin-dialog input,.admin-dialog textarea,.admin-dialog select{width:100%;margin-top:5px}.admin-dialog textarea{min-height:80px}.admin-dialog>div:last-child{display:flex;justify-content:flex-end;gap:8px;margin-top:18px}.admin-notice{position:fixed;right:24px;bottom:24px;background:#30322f;color:#fff;padding:10px 15px;border-radius:8px}
</style>
