<script setup>
import { computed, reactive, ref, watch } from 'vue'
import AdminSystem from './components/AdminSystem.vue'
const role=ref('admin'),page=ref('overview'),selected=ref('abstract'),search=ref(''),commentText=ref(''),toast=ref('')
const initial={status:'SUBMITTED',version:1,comments:[],scores:{structure:0,content:0,method:0,writing:0},summary:'',history:[{action:'提交',text:'学生提交论文 V1，系统自动锁定文档',time:'2026-07-20 09:30',version:1}]}
const state=reactive(JSON.parse(localStorage.getItem('vue3-review-state')||'null')||initial)
const sections=[['abstract','摘要','本文分析生成式人工智能在高校教学中的典型应用，从教学设计、学习支持和评价反馈三个维度讨论其价值，并关注内容可信度、学术诚信和数据安全等风险。'],['intro','一、引言','大语言模型正在改变知识获取和内容生产方式。高校需要重新审视教学目标，将知识记忆转向问题定义、证据判断和创造性解决问题等高阶能力。'],['method','二、研究方法','研究采用文献分析与半结构化访谈方法，选取三所高校的教师和学生作为观察对象，对工具使用场景、学习成效以及潜在风险进行归纳编码。'],['finding','三、研究发现','生成式人工智能能够提升备课效率并缩短形成性反馈周期；若缺乏过程监管，学生可能产生依赖，并面临虚构引用和隐私泄露问题。'],['conclusion','四、结论与建议','高校应建立分级使用规范，并通过口头答辩、过程日志与版本追踪，使人工智能成为思维脚手架而非答案替代品。']]
const dims=[['structure','结构与逻辑',20],['content','内容与观点',35],['method','方法与论证',25],['writing','规范与表达',20]]
const total=computed(()=>Object.values(state.scores).reduce((a,b)=>a+(+b||0),0)),grade=computed(()=>total.value>=90?'A':total.value>=80?'B':total.value>=70?'C':total.value>=60?'D':total.value?'F':'—')
const statusMap={SUBMITTED:['已提交 · 文档锁定','blue'],REVIEWING:['批阅中 · 文档锁定','blue'],RETURNED:['已退回 · 可修改','orange'],GRADED:['已评分 · 已归档','green']}
watch(state,v=>localStorage.setItem('vue3-review-state',JSON.stringify(v)),{deep:true});watch(role,v=>page.value=v==='teacher'?'queue':'overview')
function msg(t){toast.value=t;setTimeout(()=>toast.value='',1900)}function now(){return new Date().toLocaleString('zh-CN',{hour12:false})}function record(action,text){state.history.push({action,text,time:now(),version:state.version})}
function addComment(){if(!commentText.value.trim())return msg('请输入批注内容');state.comments.push({section:selected.value,text:commentText.value.trim(),time:now(),version:state.version});state.status='REVIEWING';record('批注',`教师在“${sections.find(s=>s[0]===selected.value)[1]}”添加定位评语`);commentText.value='';msg('批注已添加到对应位置')}
function saveReview(){state.status='REVIEWING';record('保存批阅','教师保存当前批注、评分和总评草稿');msg('批阅进度已保存')}
function returnPaper(){if(!state.comments.length&&!state.summary.trim())return msg('退回前请填写修改意见');state.status='RETURNED';record('退回修改','教师退回论文，学生端解除锁定');msg('论文已退回，学生可修改')}
function finalize(){if(!total.value||!state.summary.trim())return msg('请完成评分并填写总评');state.status='GRADED';record('完成评分',`成绩 ${total.value} 分（${grade.value}）已归档`);msg('评分已完成')}
function resubmit(){if(state.status!=='RETURNED')return msg('仅退回状态可以重新提交');state.version++;state.status='SUBMITTED';state.scores={structure:0,content:0,method:0,writing:0};state.summary='';record('重新提交',`学生修订后提交 V${state.version}，文档再次锁定`);msg('新版本已提交并锁定')}
</script>
<template><div class="shell"><aside><div class="brand"><i>文</i><div><b>论文生成系统</b><small>一体化论文工作平台</small></div></div><label>切换系统角色</label><select v-model="role"><option value="admin">管理员</option><option value="teacher">教师</option><option value="student">学生</option></select><nav v-if="role==='admin'"><button class="on">▦ 管理员系统</button></nav><nav v-else-if="role==='student'"><button :class="{on:page==='overview'}" @click="page='overview'">▦ 我的论文</button><button :class="{on:page==='feedback'}" @click="page='feedback'">◷ 批阅反馈</button></nav><nav v-else><button :class="{on:page==='queue'}" @click="page='queue'">▦ 待批阅论文</button><button :class="{on:page==='review'}" @click="page='review'">✎ 当前批阅</button><button :class="{on:page==='history'}" @click="page='history'">◷ 版本历史</button></nav><div class="user">{{role==='teacher'?'陈教授 · TEACHER':role==='admin'?'管理员 · ADMIN':'张明 · STUDENT'}}</div></aside><main><header><h1>{{role==='admin'?'管理员系统':role==='student'?(page==='overview'?'我的论文':'教师批阅反馈'):(page==='queue'?'待批阅论文':page==='review'?'论文批阅工作台':'版本历史记录')}}</h1><div v-if="role!=='admin'" class="state" :class="statusMap[state.status][1]">{{statusMap[state.status][0]}}　{{state.status==='RETURNED'?'🔓':'🔒'}}</div></header><div class="content" :class="{flush:role==='admin'}">
<AdminSystem v-if="role==='admin'" />
<template v-else-if="role==='student'"><section v-if="page==='overview'" class="card"><div class="cardhead"><b>我的论文</b><span class="mini" :class="statusMap[state.status][1]">{{statusMap[state.status][0]}}</span></div><div class="row student-row"><div><b>生成式人工智能在高校教学中的应用研究</b><small>课程论文 · V{{state.version}}</small></div><span>{{state.comments.length}} 条批注</span><span>{{total||'—'}} 分</span><button @click="page='feedback'">查看批阅记录</button><button v-if="state.status==='RETURNED'" class="primary" @click="resubmit">修改后重新提交</button></div><article class="student-paper"><h2>生成式人工智能在高校教学中的应用研究</h2><section v-for="s in sections" :key="s[0]"><h3>{{s[1]}}</h3><p>{{s[2]}}</p></section></article></section><section v-else class="card history"><div class="cardhead"><b>教师批注与版本历史</b><button @click="page='overview'">返回我的论文</button></div><div v-if="state.comments.length" class="feedback-list"><div v-for="(c,i) in state.comments" :key="i"><b>批注 #{{i+1}} · {{sections.find(s=>s[0]===c.section)[1]}}</b><p>{{c.text}}</p><small>V{{c.version}} · {{c.time}}</small></div></div><div v-else class="empty-state">暂无教师批注</div><div class="event" v-for="(h,i) in [...state.history].reverse()" :key="i"><i>{{state.history.length-i}}</i><div><b>{{h.action}} · V{{h.version}}</b><p>{{h.text}}</p><small>{{h.time}}</small></div></div></section></template>
<template v-else><section v-if="page==='queue'"><div class="metrics"><article><small>待批阅</small><strong>{{['SUBMITTED','REVIEWING'].includes(state.status)?1:0}}</strong></article><article><small>已退回</small><strong>{{state.status==='RETURNED'?1:0}}</strong></article><article><small>已评分</small><strong>{{state.status==='GRADED'?1:0}}</strong></article><article><small>定位批注</small><strong>{{state.comments.length}}</strong></article></div><div class="card"><div class="cardhead"><b>课程论文提交列表</b><input v-model="search" placeholder="搜索学生或论文标题"></div><div class="row" v-if="'张明 生成式人工智能在高校教学中的应用研究'.includes(search)"><div><b>生成式人工智能在高校教学中的应用研究</b><small>张明 · 2023110208 · V{{state.version}}</small></div><span>课程论文<small>类型</small></span><span>{{state.comments.length}} 条<small>批注</small></span><span>{{total}} 分<small>评分</small></span><button class="primary" @click="page='review'">进入批阅</button></div></div></section><section v-else-if="page==='review'" class="review"><article class="paper card"><div class="notice">{{state.status==='RETURNED'?'论文已退回，当前批阅只读。':state.status==='GRADED'?'评分已归档，当前批阅只读。':'学生提交后文档已锁定，教师可批注但不能改写原文。'}}</div><div class="title"><h2>生成式人工智能在高校教学中的应用研究</h2><p>张明 · 2023110208　|　课程论文</p></div><section v-for="s in sections" :key="s[0]" class="para" :class="{selected:selected===s[0]}" @click="selected=s[0]"><button :class="{has:state.comments.some(c=>c.section===s[0])}">{{state.comments.filter(c=>c.section===s[0]).length||'+'}}</button><h3>{{s[1]}}</h3><p>{{s[2]}}</p></section></article><aside class="tools"><div class="box"><h3>定位批注</h3><small>当前位置：{{sections.find(s=>s[0]===selected)[1]}}</small><textarea v-model="commentText" placeholder="输入该位置的评语"></textarea><button class="primary" :disabled="['RETURNED','GRADED'].includes(state.status)" @click="addComment">添加批注</button><div class="comments"><div v-for="(c,i) in state.comments" :key="i"><b>#{{i+1}} {{sections.find(s=>s[0]===c.section)[1]}}</b><p>{{c.text}}</p><small>V{{c.version}} · {{c.time}}</small></div></div></div><div class="box"><h3>评分与总评</h3><label v-for="d in dims" :key="d[0]">{{d[1]}}（{{d[2]}}分）<input v-model.number="state.scores[d[0]]" type="number" min="0" :max="d[2]" :disabled="['RETURNED','GRADED'].includes(state.status)"></label><div class="total">总分 / 等级 <strong>{{total}} / {{grade}}</strong></div><textarea v-model="state.summary" placeholder="教师总评"></textarea><div class="actions"><button @click="saveReview">保存</button><button class="danger" @click="returnPaper">退回修改</button><button class="primary" @click="finalize">完成评分</button></div></div></aside></section><section v-else class="card history"><div class="cardhead"><b>完整版本与操作留痕</b></div><div class="event" v-for="(h,i) in [...state.history].reverse()" :key="i"><i>{{state.history.length-i}}</i><div><b>{{h.action}} · V{{h.version}}</b><p>{{h.text}}</p><small>{{h.time}}</small></div></div></section></template>
</div></main><div class="toast" v-if="toast">{{toast}}</div></div></template>
